import taxonomy from '../../../data/syverro_taxonomy.json';
import booksData from '../../../data/books.json';

export const COUNTRIES = [
  'Russia',
  'Ukraine',
  'Belarus',
  'Kazakhstan',
  'Armenia',
  'Azerbaijan',
  'Georgia',
  'Moldova',
  'Kyrgyzstan',
  'Uzbekistan',
  'Tajikistan',
  'Turkmenistan',
  'Serbia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Montenegro',
  'North Macedonia',
  'Albania',
  'Bulgaria',
  'Romania',
  'Austria',
  'Belgium',
  'United Kingdom',
  'Hungary',
  'Germany',
  'Greece',
  'Denmark',
  'Ireland',
  'Spain',
  'Italy',
  'Netherlands',
  'Norway',
  'Poland',
  'Portugal',
  'Slovakia',
  'Slovenia',
  'Finland',
  'France',
  'Czech Republic',
  'Switzerland',
  'Sweden',
  'Estonia',
  'Latvia',
  'Lithuania',
  'China',
  'India',
  'Israel',
  'Turkey',
  'South Korea',
  'Japan',
  'Argentina',
  'Brazil',
  'Canada',
  'Colombia',
  'Mexico',
  'USA',
  'Chile',
  'Egypt',
  'Iran',
  'UAE',
  'Australia',
  'New Zealand',
];

export const LANGUAGES = [
  'Russian',
  'English',
  'Kazakh',
  'Ukrainian',
  'Belarusian',
  'Serbian',
  'Armenian',
  'Azerbaijani',
  'Georgian',
  'Kyrgyz',
  'Uzbek',
  'Tajik',
  'Turkmen',
  'Moldovan',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Bosnian',
  'Montenegrin',
  'Macedonian',
  'Albanian',
  'Estonian',
  'Latvian',
  'Lithuanian',
  'German',
  'French',
  'Spanish',
  'Italian',
  'Portuguese',
  'Dutch',
  'Polish',
  'Czech',
  'Slovak',
  'Hungarian',
  'Greek',
  'Danish',
  'Swedish',
  'Norwegian',
  'Finnish',
  'Irish',
  'Chinese',
  'Japanese',
  'Korean',
  'Turkish',
  'Arabic',
  'Hebrew',
  'Hindi',
  'Persian',
];

export const MOODS = taxonomy.mood;
export const THEMES = taxonomy.themes;
export const MOTIFS = taxonomy.motifs;
export const VIBES = taxonomy.vibe;

const rawGenres = booksData.flatMap((book: any) => book.genres || []);
const cleanGenres = rawGenres.filter((genre: string) => {
  if (!genre || typeof genre !== 'string') return false;
  if (genre.length < 2) return false;
  if (/^\d+$/.test(genre)) return false;
  if (/^[\d\.]+$/.test(genre)) return false;
  if (/^[A-ZА-Я]$/.test(genre)) return false;
  return true;
});
export const GENRES = Array.from(new Set(cleanGenres)).sort();

export const ERAS = [
  { value: 'ancient', label: 'Ancient World (before V c.)' },
  { value: '5c', label: 'V century' },
  { value: '6c', label: 'VI century' },
  { value: '7c', label: 'VII century' },
  { value: '8c', label: 'VIII century' },
  { value: '9c', label: 'IX century' },
  { value: '10c', label: 'X century' },
  { value: '11c', label: 'XI century' },
  { value: '12c', label: 'XII century' },
  { value: '13c', label: 'XIII century' },
  { value: '14c', label: 'XIV century' },
  { value: '15c', label: 'XV century' },
  { value: '16c', label: 'XVI century' },
  { value: '17c', label: 'XVII century' },
  { value: '18c', label: 'XVIII century' },
  { value: '19c', label: 'XIX century' },
  { value: '20c', label: 'XX century' },
  { value: '21c', label: 'XXI century' },
  { value: 'future', label: 'Future (not published)' },
];

export const ERAS_LABELS = ERAS.map(e => e.label);