package com.syverro.ui.theme

import androidx.compose.ui.graphics.Color

// Dark theme palette — deep navy, muted blue, off-white
val DarkBackground = Color(0xFF0B1220)
val DarkSurface = Color(0xFF0E1A26)
val DarkSurfaceAlt = Color(0xFF121F2E)
val DarkSurfaceHover = Color(0xFF1A2A3A)
val DarkTextPrimary = Color(0xFFE7EDF5)
val DarkTextSecondary = Color(0xFF97A6BA)
val DarkTextMuted = Color(0xFF6E7C90)
val DarkPrimary = Color(0xFF5C7C9A)
val DarkPrimarySoft = Color(0xFF3A5570)
val DarkAccent = Color(0xFFA8B0BA)
val DarkAccentSoft = Color(0xFF2C3F55)
val DarkSuccess = Color(0xFF6B9B7A)
val DarkWarning = Color(0xFFD4A76A)
val DarkError = Color(0xFFC47A7A)
val DarkInfo = Color(0xFF7A9BC4)
val DarkBorder = Color(0x1E8CAAC8)
val DarkCard = Color(0xFF0E1A26)
val DarkChip = Color(0xFF1B2A3A)
val DarkChipActive = Color(0xFF2C3F55)

// Light theme palette — warm beige, muted slate, warm dark (aligned to DESIGN_SYSTEM.md)
val LightBackground = Color(0xFFE0D4C3)
val LightSurface = Color(0xFFD4C7B4)
val LightSurfaceAlt = Color(0xFFE8DDCE)
val LightSurfaceHover = Color(0xFFCEC1AE)
val LightTextPrimary = Color(0xFF2A2622)
val LightTextSecondary = Color(0xFF6B6358)
val LightTextMuted = Color(0xFF948A7C)
val LightPrimary = Color(0xFF4A5A6A)
val LightPrimarySoft = Color(0xFF6B7A88)
val LightAccent = Color(0xFFB8A99A)
val LightAccentSoft = Color(0xFFD1C6BA)
val LightSuccess = Color(0xFF6B8F7A)
val LightWarning = Color(0xFFD4A76A)
val LightError = Color(0xFFC47A7A)
val LightInfo = Color(0xFF7A8FC4)
val LightBorder = Color(0x33BEB09C)
val LightCard = Color(0xFFD7C8B5)
val LightChip = Color(0xFFC8BAA6)
val LightChipActive = Color(0xFFBEB09C)